FROM golang:1.20-alpine3.17
LABEL email="linho301150@gmail.com"

ARG ACCESSKEYID_ARG
ARG ACCESSKEYSECRET_ARG
ARG API_KEY_ARG

ENV GO111MODULE=on
ENV ACCESSKEYID=$ACCESSKEYID_ARG
ENV ACCESSKEYSECRET=$ACCESSKEYSECRET_ARG
ENV API_KEY=API_KEY_ARG

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /app
COPY go.* ./
RUN go mod download

COPY ./ ./
RUN go build

CMD ["./linho1150"]